name: Python setup
description: Configure Python and install Python dependencies

runs:
  using: composite
  steps:
    - name: 📖 Checkout commit locally
      uses: actions/checkout@v3

    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
        cache: pip

    - name: 📦 Install poetry and dependencies
      shell: bash
      working-directory: ./backend
      run: |
        pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry lock --check --no-update  # Check lock file is consistent with pyproject.toml
        poetry install --with dev
